#!/bin/bash
set -euo pipefail

REPO="$1"
NUM="$2"

CHOICE=$(gum choose --header "Are you sure you want to merge PR #$NUM?" "Yes" "No" < /dev/tty)
if [[ "$CHOICE" == "Yes" ]]; then
  gh pr merge "$NUM" --repo "$REPO" --squash --delete-branch
fi
