#!/bin/bash

[ -n "$MAIN_SESSION" ] && tmux -L default set -t "$MAIN_SESSION" @claude_status "" 2>/dev/null || true

# Disable automatic window renaming so titles persist in the popup session
tmux set-option automatic-rename off
tmux rename-window "shell"
tmux set-option status-left "#[bg=#252534,fg=#7E9CD8] popup "
exec $SHELL
