#!/bin/bash

for x in "$@"; do
  if [ ! -e "$x" ]; then
    gum log --level warn "trash: '$x' does not exist" >&2
    continue
  fi
  base=$(basename "$x")
  uuid=$(uuidgen | tr '[:upper:]' '[:lower:]')
  dest="$HOME/.Trash/$base.$uuid"
  mv -- "$x" "$dest"
done
