#!/bin/bash

# This script is designed to alert me to take a break.
log_file="/tmp/luncher.log"
current_date=$(date +"%Y-%m-%d %H:%M:%S")

log () {
  echo "$(date +'%Y-%m-%d %H:%M:%S') - $1" >> "$log_file"
}

say "Break time!"
log "Luncher ran"
