#!/bin/bash

# Uninstaller for Luncher
launchctl unload "/Users/${USER}/Library/LaunchAgents/luncher.plist"
if [[ -L "/Users/$USER/Library/LaunchAgents/luncher.plist" ]]; then
  rm "/Users/$USER/Library/LaunchAgents/luncher.plist"
fi

if [[ -L "/Users/$USER/bin/luncher" ]]; then
  rm "/Users/$USER/bin/luncher"
fi

echo "Uninstalled luncher" 

