#!/bin/bash

# This script is designed to alert me to take a break.
log_file="/tmp/tracker.log"
current_date=$(date +"%Y-%m-%d %H:%M:%S")

log () {
  echo "$(date +'%Y-%m-%d %H:%M:%S') $1" >> "$log_file"
}

# Script calls the shutdown command which shuts the computer down in one Minute.
COUNT=$(netstat aux -tuln | grep "irdmi" | awk '/ESTABLISHED$/ {print $0}' | wc -l)
TRIMMED_COUNT=$(echo $COUNT | xargs)

if [[ "$TRIMMED_COUNT" == "0" ]]; then
  log "{ \"status\": \"not_running\" }"
  sudo shutdown -h +1 
else
  log "{ \"status\": \"running\" }"
fi
  

