#!/bin/bash

# Uninstaller for Tracker
launchctl unload "/Users/${USER}/Library/LaunchAgents/tracker.plist"
if [[ -L "/Users/$USER/Library/LaunchAgents/tracker.plist" ]]; then
  rm "/Users/$USER/Library/LaunchAgents/tracker.plist"
fi

if [[ -L "/Users/$USER/bin/tracker" ]]; then
  rm "/Users/$USER/bin/tracker"
fi

echo "Uninstalled tracker" 

